apiVersion: v1
kind: Namespace
metadata: {name: rocketchat}
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-conn
  namespace: rocketchat

stringData:
  connectionString: nats://nats-mesh.nats.svc.cluster.local:4222
