apiVersion: v1
kind: Namespace
metadata: {name: nats}
---
apiVersion: v1
kind: Service
metadata:
  name: nats-mesh
  namespace: nats
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
spec:
  type: ClusterIP
  ports:
    - port: 6222
      name: cluster
    - port: 4222
      name: client
  selector:
    app.kubernetes.io/name: nats

